package View;

import dss.*;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 10
 */
public class Menu_admin extends javax.swing.JFrame {
    
    private Facade fac;

    /**
     * Creates new form Menu_admin
     */
    public Menu_admin(Facade f) {
        initComponents();
        this.fac = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Adicionar_Uti = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtpass2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();
        Atualizar_Uti = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome_atu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pass_aut = new javax.swing.JPasswordField();
        cancelar_Atu = new javax.swing.JButton();
        Submeter_Auto = new javax.swing.JButton();
        Remover_Uti = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nome_rem = new javax.swing.JTextField();
        cancelar_rem = new javax.swing.JButton();
        confirma_rem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu administrador");
        setResizable(false);

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Adicionar Utilizador");

        jLabel1.setText("Nome:");

        jLabel2.setText("Palavra Passe:");

        jLabel4.setText("Confirmar a palavra passe:");

        txtpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de conta:");

        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fabricante", "Vendedor" }));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Adicionar_UtiLayout = new javax.swing.GroupLayout(Adicionar_Uti);
        Adicionar_Uti.setLayout(Adicionar_UtiLayout);
        Adicionar_UtiLayout.setHorizontalGroup(
            Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                .addGroup(Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                        .addGroup(Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel5))
                            .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                                .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar))
                            .addGroup(Adicionar_UtiLayout.createSequentialGroup()
                                .addGroup(Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 58, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Adicionar_UtiLayout.setVerticalGroup(
            Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Adicionar_UtiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(Adicionar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(cancelar))
                .addGap(50, 50, 50))
        );

        jPanel2.add(Adicionar_Uti, "Adicionar_Uti");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setText("Atualizar Utilizador");

        jLabel7.setText("Nome:");

        jLabel8.setText("Nova Palavra Passe:");

        cancelar_Atu.setText("Cancelar");
        cancelar_Atu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_AtuActionPerformed(evt);
            }
        });

        Submeter_Auto.setText("Submeter");
        Submeter_Auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submeter_AutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Atualizar_UtiLayout = new javax.swing.GroupLayout(Atualizar_Uti);
        Atualizar_Uti.setLayout(Atualizar_UtiLayout);
        Atualizar_UtiLayout.setHorizontalGroup(
            Atualizar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Atualizar_UtiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Atualizar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Atualizar_UtiLayout.createSequentialGroup()
                        .addComponent(cancelar_Atu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Submeter_Auto))
                    .addGroup(Atualizar_UtiLayout.createSequentialGroup()
                        .addGroup(Atualizar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_atu, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(pass_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Atualizar_UtiLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Atualizar_UtiLayout.setVerticalGroup(
            Atualizar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Atualizar_UtiLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addGap(57, 57, 57)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_atu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(Atualizar_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submeter_Auto)
                    .addComponent(cancelar_Atu))
                .addGap(36, 36, 36))
        );

        jPanel2.add(Atualizar_Uti, "Atualizar_Uti");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setText("Remover Utilizador");

        jLabel10.setText("Nome:");

        nome_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_remActionPerformed(evt);
            }
        });

        cancelar_rem.setText("Cancelar");
        cancelar_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_remActionPerformed(evt);
            }
        });

        confirma_rem.setText("Confirmar");
        confirma_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirma_remActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Remover_UtiLayout = new javax.swing.GroupLayout(Remover_Uti);
        Remover_Uti.setLayout(Remover_UtiLayout);
        Remover_UtiLayout.setHorizontalGroup(
            Remover_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Remover_UtiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Remover_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Remover_UtiLayout.createSequentialGroup()
                        .addComponent(cancelar_rem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirma_rem))
                    .addGroup(Remover_UtiLayout.createSequentialGroup()
                        .addGroup(Remover_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(nome_rem, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Remover_UtiLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Remover_UtiLayout.setVerticalGroup(
            Remover_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Remover_UtiLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel9)
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nome_rem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(Remover_UtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_rem)
                    .addComponent(confirma_rem))
                .addContainerGap())
        );

        jPanel2.add(Remover_Uti, "Remover_Uti");

        jMenu1.setText("Opções");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Adicionar Utilizador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Remover Utilizador");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Atualizar Utilizador");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout c1 = (CardLayout) jPanel2.getLayout(); 
        c1.show(jPanel2,"Adicionar_Uti");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
          new LogIn(this.fac).setVisible(true);
          this.setVisible(false);
        
    }//GEN-LAST:event_cancelarActionPerformed

    private void cancelar_AtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_AtuActionPerformed
          new LogIn(this.fac).setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_cancelar_AtuActionPerformed

    private void nome_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_remActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_remActionPerformed

    private void cancelar_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_remActionPerformed
          new LogIn(this.fac).setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_cancelar_remActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout c1 = (CardLayout) jPanel2.getLayout(); 
        c1.show(jPanel2,"Remover_Uti");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout c1 = (CardLayout) jPanel2.getLayout(); 
        c1.show(jPanel2,"Atualizar_Uti");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass2ActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        String nome = txtNome.getText();
        String pass = txtpass.getText();
        String confirmapass = txtpass2.getText();
        String tipo = txtTipo.getSelectedItem().toString();
        try{
            if (pass.equals(confirmapass)){
                this.fac.addUtilizador(nome,pass,tipo);
                if(tipo.equals("Vendedor")){
                    JOptionPane.showMessageDialog(null,"Vendedor criado com sucesso!");
                }
                if(tipo.equals("Fabricante")){
                    JOptionPane.showMessageDialog(null,"Fabricante criado com sucesso!");
                }
            }
            else {JOptionPane.showMessageDialog(null,"A palavra-passe de confirmação está errada, escreva de novo!");}
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void confirma_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirma_remActionPerformed
        String user = nome_rem.getText();
        try{
            fac.removeUtilizador(user);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_confirma_remActionPerformed

    private void Submeter_AutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submeter_AutoActionPerformed
        String nome = nome_atu.getText();
        String pass = pass_aut.getText();
        try{
            fac.updateUtilizador(nome,pass);
            JOptionPane.showMessageDialog(null,"Palavra-passe alterada com sucesso!");
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_Submeter_AutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin(new Facade()).setVisible(true);
            }
            });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adicionar_Uti;
    private javax.swing.JPanel Atualizar_Uti;
    private javax.swing.JButton Confirmar;
    private javax.swing.JPanel Remover_Uti;
    private javax.swing.JButton Submeter_Auto;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar_Atu;
    private javax.swing.JButton cancelar_rem;
    private javax.swing.JButton confirma_rem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nome_atu;
    private javax.swing.JTextField nome_rem;
    private javax.swing.JPasswordField pass_aut;
    private javax.swing.JTextField txtNome;
    private javax.swing.JComboBox<String> txtTipo;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass2;
    // End of variables declaration//GEN-END:variables
}
